WebSocket: fix error object on connection error (#373)
# Description
On a websocket connection error, the error thrown by the SDK has the following message: `[object Object]`

This is because on a connection error, `ws` sends a complex object, but our error handler processes it as if it's a string.

# How to test it
Run this snippet:

```js
const {Kuzzle, WebSocket} = require('kuzzle-sdk');
const
  ws = new WebSocket('localhost'),
  kuzzle = new Kuzzle(ws);

kuzzle.connect().catch(err => console.error(err));
kuzzle.disconnect();
```

Before this PR, this prints:

```
Error: [object Object]
    ... stack trace ...
```
With this PR:

```
Error: WebSocket was closed before the connection was established
    ... stack trace ...
```

* [websocket] fix error object on connection error
* [ws] do not overwrite an existing stacktrace