Add more context to errors (#669)
⚠️ Depends on #619 

## What does this PR do ?
This PR adds more context from the Kuzzle error response to the error objects (**KuzzleError**): ```controller, action, volatile, index, collection```

New error output example:
```
 NotFoundError: API action "foo":"bar" not found
          |
          |
          Status: 404
          Controller: foo
          Action: bar
          KuzzleAbstractProtocol
          |
          |
       at KuzzleAbstractProtocol.query (/Users/clementbolin/Epitech/Kuzzle/sdk-javascript/src/protocols/abstract/Base.ts:37:6)
>    at Context.<anonymous> (/Users/clementbolin/Epitech/Kuzzle/sdk-javascript/test/protocol/Base.test.js:215:23)
       at callFn (/Users/clementbolin/Epitech/Kuzzle/sdk-javascript/node_modules/mocha/lib/runnable.js:366:21)
       at Test.Runnable.run (/Users/clementbolin/Epitech/Kuzzle/sdk-javascript/node_modules/mocha/lib/runnable.js:354:5)
       ...
```
### How should this be manually tested?
```npm run test:unit```
or
```npm run test```